// GENERATED by tools/design-system/build_tokens.py from docs/02-brand/tokens.json
// and docs/07-design-system/tokens/tokens.json. Do not edit by hand.
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

/// Brand palette (docs/02-brand/palette.md). Prefer DdColors roles in widgets.
abstract final class DdPalette {
  /// شب — from logo outline
  static const Color brandInk = Color(0xFF061720);
  /// برگ — from logo body
  static const Color brandLeaf = Color(0xFF85C06C);
  /// جوانه — from logo highlight
  static const Color brandSprout = Color(0xFFDFF8CF);
  /// جنگل — completes the palette; accessible green text on light
  static const Color brandForest = Color(0xFF346856);
  static const Color green50 = Color(0xFFF1FCEA);
  static const Color green100 = Color(0xFFDFF8CF);
  static const Color green200 = Color(0xFFBBE2A8);
  static const Color green300 = Color(0xFF9ED088);
  static const Color green400 = Color(0xFF85C06C);
  static const Color green500 = Color(0xFF659E65);
  static const Color green600 = Color(0xFF4C825E);
  static const Color green700 = Color(0xFF346856);
  static const Color green800 = Color(0xFF1D423D);
  static const Color green900 = Color(0xFF102A2D);
  static const Color neutral50 = Color(0xFFF3F8FA);
  static const Color neutral100 = Color(0xFFE8EEF1);
  static const Color neutral200 = Color(0xFFD6DEE3);
  static const Color neutral300 = Color(0xFFB9C3C9);
  static const Color neutral400 = Color(0xFF95A0A7);
  static const Color neutral500 = Color(0xFF758188);
  static const Color neutral600 = Color(0xFF58656D);
  static const Color neutral700 = Color(0xFF3C4A52);
  static const Color neutral800 = Color(0xFF223038);
  static const Color neutral900 = Color(0xFF0F1E26);
  /// طلا — medals and achievements (approved, D-030)
  static const Color semanticMedal = Color(0xFFF2B33D);
  /// medal text on light backgrounds (approved)
  static const Color semanticMedalText = Color(0xFF8A5A00);
  /// system errors only, never for "no" (approved, D-030)
  static const Color semanticError = Color(0xFFB83A30);
  /// error on dark theme (approved)
  static const Color semanticErrorDark = Color(0xFFFF8A7A);
}

/// Pixel system rules (visual-identity.md §5).
abstract final class DdPixel {
  /// one 'pixel' of the brand grid; all spacing and sizes are multiples
  static const double unit = 4;
  static const double outlineWidth = 2;
  /// hard drop downward, no blur — like the thick base of the logo check
  static const double shadowOffset = 4;
  /// no rounded corners; use stepped (notched) corners instead
  static const double radius = 0;
}

/// Spacing scale, multiples of the 4dp brand pixel.
abstract final class DdSpace {
  static const double s0 = 0;
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  /// screen side margin
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
}

/// Fixed sizes. Pixel art only at integer scales.
abstract final class DdSize {
  /// minimum touch target
  static const double touchMin = 48;
  /// 1 icon pixel = 2dp
  static const double iconMd = 24;
  /// 1 icon pixel = 3dp
  static const double iconLg = 36;
  /// 1 icon pixel = 4dp
  static const double iconXl = 48;
  /// pixel numeral 21dp tall
  static const double numeralUnitSm = 3;
  /// 28dp tall
  static const double numeralUnitMd = 4;
  /// 42dp tall
  static const double numeralUnitLg = 6;
  /// 56dp tall
  static const double numeralUnitXl = 8;
  /// 16px sprite x3
  static const double characterSm = 48;
  /// x6
  static const double characterMd = 96;
  /// x10
  static const double characterLg = 160;
  /// content width on tablets
  static const double contentMax = 480;
}

/// Stepped corners, outlines and borders.
abstract final class DdShape {
  /// stepped corner: one 4dp square cut from each corner
  static const double notch = 4;
  /// chips and small cells
  static const double notchSm = 2;
  static const double outline = 2;
  /// plain fields and dividers use border color, square corners
  static const double border = 2;
  static const double divider = 1;
}

/// Hard shadow offsets (straight down, no blur).
abstract final class DdElevation {
  /// hard shadow straight down, no blur
  static const double rest = 4;
  /// chips, small cells
  static const double low = 2;
  /// component moves down by rest offset, shadow disappears
  static const double pressed = 0;
}

/// Durations. Respect reduced motion: use DdMotion.instant.
abstract final class DdMotion {
  static const Duration instant = Duration(milliseconds: 0);
  /// press, toggle
  static const Duration fast = Duration(milliseconds: 80);
  /// state change, chip
  static const Duration base = Duration(milliseconds: 120);
  /// sheet, card enter
  static const Duration slow = Duration(milliseconds: 200);
  /// signature: check builds pixel by pixel after yes
  static const Duration check = Duration(milliseconds: 480);
  /// level and medal moments
  static const Duration celebrate = Duration(milliseconds: 1200);
}

/// Stepped curves and sprite frame rate.
abstract final class DdMotionSteps {
  /// steps() count for fast/base
  static const int stepsShort = 2;
  /// steps() count for slow
  static const int stepsLong = 4;
  /// character animation, 4 to 8 allowed
  static const int spriteFps = 6;
}

/// Stacking order.
abstract final class DdZ {
  static const int base = 0;
  static const int sticky = 10;
  static const int fab = 20;
  static const int sheet = 30;
  static const int dialog = 40;
  static const int toast = 50;
}

/// Component dimensions (docs/07-design-system/components.md).
abstract final class DdComponent {
  static const double buttonHeight = 48;
  static const double buttonHeightSm = 40;
  static const double buttonPaddingX = 20;
  static const double answerHeight = 56;
  static const double answerGap = 12;
  static const double fieldHeight = 52;
  static const double fieldPaddingX = 16;
  static const double cardPadding = 16;
  static const double cardGap = 12;
  static const double chipHeight = 36;
  static const double chipPaddingX = 12;
  static const double chainCellSize = 16;
  static const double chainCellGap = 4;
  static const double calendarCellSize = 40;
  /// 4 brand pixels incl. outline
  static const double progressBarHeight = 16;
  /// fill grows in whole 4dp segments
  static const double progressBarSegment = 4;
  /// pixel adherence ring, 28 units of 4dp
  static const double ringSize = 112;
  static const double ringThickness = 12;
  static const double tabBarHeight = 64;
  static const double fabSize = 56;
  static const double sheetHandleWidth = 32;
  static const double sheetPadding = 24;
}

/// Type scale (Estedad). Large numbers use the pixel numerals, not these styles.
abstract final class DdType {
  static const String fontFamily = 'Estedad';
  static const List<String> fontFamilyFallback = ['Tahoma', 'sans-serif'];
  static const TextStyle display = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 32,
    height: 1.375,
    fontWeight: FontWeight.w900,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle question = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 22,
    height: 1.6364,
    fontWeight: FontWeight.w800,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle title1 = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 20,
    height: 1.6,
    fontWeight: FontWeight.w700,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle title2 = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 17,
    height: 1.6471,
    fontWeight: FontWeight.w700,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle answer = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 18,
    height: 1.5556,
    fontWeight: FontWeight.w800,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle button = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 16,
    height: 1.5,
    fontWeight: FontWeight.w700,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle body = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 15,
    height: 1.7333,
    fontWeight: FontWeight.w400,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle small = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 13,
    height: 1.6923,
    fontWeight: FontWeight.w500,
    fontFeatures: [FontFeature.tabularFigures()],
  );
  static const TextStyle label = TextStyle(
    fontFamily: fontFamily,
    fontFamilyFallback: fontFamilyFallback,
    fontSize: 12,
    height: 1.6667,
    fontWeight: FontWeight.w600,
    fontFeatures: [FontFeature.tabularFigures()],
  );
}

/// Semantic color roles for one theme. Widgets read colors only from here.
@immutable
class DdColors {
  const DdColors({
    required this.bg,
    required this.surface,
    required this.surfaceTint,
    required this.text,
    required this.textMuted,
    required this.outline,
    required this.border,
    required this.primary,
    required this.onPrimary,
    required this.primaryPressed,
    required this.yes,
    required this.yesText,
    required this.noText,
    required this.noBorder,
    required this.focus,
    required this.medal,
    required this.medalText,
    required this.error,
    required this.surfaceSunken,
    required this.surfacePressed,
    required this.track,
    required this.scrim,
    required this.disabledBg,
    required this.disabledText,
    required this.chainYes,
    required this.chainFreeze,
    required this.chainNo,
    required this.chainOff,
    required this.xpFill,
    required this.onMedal,
    required this.highlight,
    required this.shadow,
  });

  final Color bg;
  final Color surface;
  final Color surfaceTint;
  final Color text;
  final Color textMuted;
  final Color outline;
  final Color border;
  final Color primary;
  final Color onPrimary;
  final Color primaryPressed;
  final Color yes;
  final Color yesText;
  final Color noText;
  final Color noBorder;
  final Color focus;
  final Color medal;
  final Color medalText;
  final Color error;
  /// tracks, inactive cells
  final Color surfaceSunken;
  final Color surfacePressed;
  /// empty part of bars and rings
  final Color track;
  /// behind sheets and dialogs (شب، ۴۸٪)
  final Color scrim;
  final Color disabledBg;
  final Color disabledText;
  final Color chainYes;
  final Color chainFreeze;
  final Color chainNo;
  /// day not scheduled
  final Color chainOff;
  final Color xpFill;
  final Color onMedal;
  /// 2dp top light on primary buttons (from the logo)
  final Color highlight;
  /// hard pixel shadow
  final Color shadow;

  static const light = DdColors(
    bg: Color(0xFFF1FCEA),
    surface: Color(0xFFFFFFFF),
    surfaceTint: Color(0xFFDFF8CF),
    text: Color(0xFF061720),
    textMuted: Color(0xFF58656D),
    outline: Color(0xFF061720),
    border: Color(0xFFD6DEE3),
    primary: Color(0xFF85C06C),
    onPrimary: Color(0xFF061720),
    primaryPressed: Color(0xFF659E65),
    yes: Color(0xFF85C06C),
    yesText: Color(0xFF346856),
    noText: Color(0xFF58656D),
    noBorder: Color(0xFF758188),
    focus: Color(0xFF061720),
    medal: Color(0xFFF2B33D),
    medalText: Color(0xFF8A5A00),
    error: Color(0xFFB83A30),
    surfaceSunken: Color(0xFFE8EEF1),
    surfacePressed: Color(0xFFDFF8CF),
    track: Color(0xFFD6DEE3),
    scrim: Color(0x7A061720),
    disabledBg: Color(0xFFE8EEF1),
    disabledText: Color(0xFF758188),
    chainYes: Color(0xFF85C06C),
    chainFreeze: Color(0xFFDFF8CF),
    chainNo: Color(0xFFD6DEE3),
    chainOff: Color(0xFFE8EEF1),
    xpFill: Color(0xFFF2B33D),
    onMedal: Color(0xFF061720),
    highlight: Color(0xFFDFF8CF),
    shadow: Color(0xFF061720),
  );

  static const dark = DdColors(
    bg: Color(0xFF061720),
    surface: Color(0xFF0F1E26),
    surfaceTint: Color(0xFF1D423D),
    text: Color(0xFFDFF8CF),
    textMuted: Color(0xFFB9C3C9),
    outline: Color(0xFF4C825E),
    border: Color(0xFF3C4A52),
    primary: Color(0xFF85C06C),
    onPrimary: Color(0xFF061720),
    primaryPressed: Color(0xFF9ED088),
    yes: Color(0xFF85C06C),
    yesText: Color(0xFF85C06C),
    noText: Color(0xFFB9C3C9),
    noBorder: Color(0xFF758188),
    focus: Color(0xFFDFF8CF),
    medal: Color(0xFFF2B33D),
    medalText: Color(0xFFF2B33D),
    error: Color(0xFFFF8A7A),
    surfaceSunken: Color(0xFF223038),
    surfacePressed: Color(0xFF102A2D),
    track: Color(0xFF3C4A52),
    scrim: Color(0xA3000000),
    disabledBg: Color(0xFF223038),
    disabledText: Color(0xFF758188),
    chainYes: Color(0xFF85C06C),
    chainFreeze: Color(0xFF1D423D),
    chainNo: Color(0xFF3C4A52),
    chainOff: Color(0xFF223038),
    xpFill: Color(0xFFF2B33D),
    onMedal: Color(0xFF061720),
    highlight: Color(0xFFDFF8CF),
    shadow: Color(0xFF000000),
  );
}
