"""Build design-system outputs from token sources. D-058.

Sources (W3C Design Tokens format):
  docs/02-brand/tokens.json                 brand colors, base themes, pixel, font
  docs/07-design-system/tokens/tokens.json  extra theme roles, space, size, shape, elevation, type, motion, component

Outputs in docs/07-design-system/tokens/:
  tokens.css            CSS custom properties (--dd-*), light/dark themes
  didit_tokens.dart     Flutter constants (no Material dependency)
  tokens.resolved.json  every token flattened with references resolved

    python3 tools/design-system/build_tokens.py           # write outputs
    python3 tools/design-system/build_tokens.py --check   # also print WCAG contrast of key pairs
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BRAND = ROOT / "docs/02-brand/tokens.json"
DS = ROOT / "docs/07-design-system/tokens/tokens.json"
OUT = ROOT / "docs/07-design-system/tokens"
REF = re.compile(r"\{([^}]+)\}")


def merge(a, b):
    for k, v in b.items():
        if isinstance(v, dict) and isinstance(a.get(k), dict) and "$value" not in v:
            merge(a[k], v)
        else:
            a[k] = v
    return a


def flatten(node, path=()):
    for k, v in node.items():
        if k.startswith("$"):
            continue
        if isinstance(v, dict) and "$value" in v:
            yield path + (k,), v
        elif isinstance(v, dict):
            yield from flatten(v, path + (k,))


def load():
    tree = merge(json.loads(BRAND.read_text("utf-8")), json.loads(DS.read_text("utf-8")))
    raw = {".".join(p): t for p, t in flatten(tree)}

    def resolve(value, seen=()):
        if isinstance(value, str):
            m = REF.fullmatch(value)
            if m:
                key = m.group(1)
                assert key in raw, f"unknown reference {{{key}}}"
                assert key not in seen, f"reference cycle at {key}"
                return resolve(raw[key]["$value"], seen + (key,))
        if isinstance(value, dict):
            return {k: resolve(v, seen) for k, v in value.items()}
        return value

    return {k: {"type": t.get("$type"), "value": resolve(t["$value"]), "description": t.get("$description", "")}
            for k, t in raw.items()}


def kebab(path):
    return "-".join(path.split("."))


def camel(parts):
    out = []
    for i, p in enumerate("-".join(parts).split("-")):
        out.append(p if i == 0 else p[:1].upper() + p[1:])
    s = "".join(out)
    return "s" + s if s[:1].isdigit() else s


def px(v):
    return float(v[:-2]) if isinstance(v, str) and v.endswith("px") else v


def num(x):
    return str(int(x)) if float(x).is_integer() else f"{x:g}"


def dart_color(h):
    h = h.lstrip("#").upper()
    a = h[6:8] if len(h) == 8 else "FF"
    return f"Color(0x{a}{h[:6]})"


# ---------- CSS ----------
def css(tokens):
    root, light, dark = [], [], []
    for k, t in tokens.items():
        v = t["value"]
        if k.startswith("theme."):
            _, mode, role = k.split(".", 2)
            (light if mode == "light" else dark).append(f"  --dd-{role}: {v};")
        elif t["type"] == "typography":
            name = kebab(k)
            root.append(f"  --dd-{name}-size: {v['fontSize']};")
            root.append(f"  --dd-{name}-line: {v['lineHeight']};")
            root.append(f"  --dd-{name}-weight: {v['fontWeight']};")
        elif t["type"] == "fontFamily":
            fam = ", ".join(f'"{f}"' if " " in f or f[0].isupper() else f for f in v)
            root.append(f"  --dd-{kebab(k)}: {fam};")
        else:
            root.append(f"  --dd-{kebab(k)}: {v};")
    head = "/* GENERATED by tools/design-system/build_tokens.py — do not edit. */\n"
    return (head + ":root {\n" + "\n".join(root) + "\n}\n"
            ":root, :root[data-theme=\"light\"] {\n" + "\n".join(light) + "\n  color-scheme: light;\n}\n"
            "@media (prefers-color-scheme: dark) {\n  :root:not([data-theme=\"light\"]) {\n"
            + "\n".join("  " + l for l in dark) + "\n    color-scheme: dark;\n  }\n}\n"
            ":root[data-theme=\"dark\"] {\n" + "\n".join(dark) + "\n  color-scheme: dark;\n}\n")


# ---------- Dart ----------
WEIGHTS = {400: "w400", 500: "w500", 600: "w600", 700: "w700", 800: "w800", 900: "w900"}


def dart(tokens):
    L = ["// GENERATED by tools/design-system/build_tokens.py from docs/02-brand/tokens.json",
         "// and docs/07-design-system/tokens/tokens.json. Do not edit by hand.",
         "// ignore_for_file: constant_identifier_names", "",
         "import 'package:flutter/widgets.dart';", ""]

    def group(cls, prefix, kind, doc):
        items = [(k, t) for k, t in tokens.items() if k.startswith(prefix + ".") and t["type"] == kind]
        if not items:
            return
        L.append(f"/// {doc}")
        L.append(f"abstract final class {cls} {{")
        for k, t in items:
            name = camel(k[len(prefix) + 1:].split("."))
            v = t["value"]
            if t["description"]:
                L.append(f"  /// {t['description']}")
            if kind == "color":
                L.append(f"  static const Color {name} = {dart_color(v)};")
            elif kind == "dimension":
                L.append(f"  static const double {name} = {num(px(v))};")
            elif kind == "duration":
                L.append(f"  static const Duration {name} = Duration(milliseconds: {int(v[:-2])});")
            elif kind == "number":
                L.append(f"  static const int {name} = {v};")
        L.append("}")
        L.append("")

    group("DdPalette", "color", "color", "Brand palette (docs/02-brand/palette.md). Prefer DdColors roles in widgets.")
    group("DdPixel", "pixel", "dimension", "Pixel system rules (visual-identity.md §5).")
    group("DdSpace", "space", "dimension", "Spacing scale, multiples of the 4dp brand pixel.")
    group("DdSize", "size", "dimension", "Fixed sizes. Pixel art only at integer scales.")
    group("DdShape", "shape", "dimension", "Stepped corners, outlines and borders.")
    group("DdElevation", "elevation", "dimension", "Hard shadow offsets (straight down, no blur).")
    group("DdMotion", "motion.duration", "duration", "Durations. Respect reduced motion: use DdMotion.instant.")
    group("DdMotionSteps", "motion", "number", "Stepped curves and sprite frame rate.")
    group("DdZ", "z", "number", "Stacking order.")
    group("DdComponent", "component", "dimension", "Component dimensions (docs/07-design-system/components.md).")

    fam = tokens["font.family"]["value"]
    L.append("/// Type scale (Estedad). Large numbers use the pixel numerals, not these styles.")
    L.append("abstract final class DdType {")
    L.append(f"  static const String fontFamily = '{fam[0]}';")
    L.append("  static const List<String> fontFamilyFallback = [" + ", ".join(f"'{f}'" for f in fam[1:]) + "];")
    for k, t in tokens.items():
        if t["type"] != "typography":
            continue
        v = t["value"]
        size, line = px(v["fontSize"]), px(v["lineHeight"])
        name = camel(k.split(".")[1:])
        L.append(f"  static const TextStyle {name} = TextStyle(")
        L.append("    fontFamily: fontFamily,")
        L.append("    fontFamilyFallback: fontFamilyFallback,")
        L.append(f"    fontSize: {num(size)},")
        L.append(f"    height: {round(line / size, 4)},")
        L.append(f"    fontWeight: FontWeight.{WEIGHTS[v['fontWeight']]},")
        L.append("    fontFeatures: [FontFeature.tabularFigures()],")
        L.append("  );")
    L.append("}")
    L.append("")

    roles = [k.split(".", 2)[2] for k in tokens if k.startswith("theme.light.")]
    L.append("/// Semantic color roles for one theme. Widgets read colors only from here.")
    L.append("@immutable")
    L.append("class DdColors {")
    L.append("  const DdColors({")
    for r in roles:
        L.append(f"    required this.{camel([r])},")
    L.append("  });")
    L.append("")
    for r in roles:
        desc = tokens[f"theme.light.{r}"]["description"]
        if desc:
            L.append(f"  /// {desc}")
        L.append(f"  final Color {camel([r])};")
    for mode in ("light", "dark"):
        L.append("")
        L.append(f"  static const {mode} = DdColors(")
        for r in roles:
            L.append(f"    {camel([r])}: {dart_color(tokens[f'theme.{mode}.{r}']['value'])},")
        L.append("  );")
    L.append("}")
    return "\n".join(L) + "\n"


# ---------- contrast ----------
def lum(h):
    h = h.lstrip("#")[:6]
    c = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    c = [x / 12.92 if x <= 0.03928 else ((x + 0.055) / 1.055) ** 2.4 for x in c]
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def ratio(a, b):
    la, lb = sorted((lum(a), lum(b)), reverse=True)
    return (la + 0.05) / (lb + 0.05)


PAIRS = [  # (foreground, background, minimum, use)
    ("text", "bg", 4.5, "متن روی زمینه"),
    ("text", "surface", 4.5, "متن روی کارت"),
    ("text-muted", "surface", 4.5, "متن فرعی روی کارت"),
    ("text-muted", "bg", 4.5, "متن فرعی روی زمینه"),
    ("yes-text", "surface", 4.5, "متن سبز «بله»"),
    ("no-text", "surface", 4.5, "متن دکمه‌ی «خیر»"),
    ("on-primary", "primary", 4.5, "متن روی دکمه‌ی اصلی"),
    ("medal-text", "surface", 4.5, "متن طلایی"),
    ("error", "surface", 4.5, "پیام خطای سیستم"),
    ("text", "surface-tint", 4.5, "متن روی سطح ملایم"),
    ("disabled-text", "disabled-bg", 3.0, "متن غیرفعال (الزام WCAG نداره)"),
    ("outline", "bg", 3.0, "خط دور اجزا"),
    ("no-border", "surface", 3.0, "لبه‌ی دکمه‌ی «خیر»"),
    ("focus", "bg", 3.0, "حلقه‌ی فوکوس"),
    ("chain-yes", "chain-off", 1.0, "خونه‌ی «بله» (با خط دور شب جدا می‌شه)"),
]


def contrast(tokens):
    rows = []
    for mode in ("light", "dark"):
        for fg, bg, need, use in PAIRS:
            a, b = tokens[f"theme.{mode}.{fg}"]["value"], tokens[f"theme.{mode}.{bg}"]["value"]
            r = ratio(a, b)
            rows.append((mode, fg, bg, r, need, use))
    return rows


def main():
    tokens = load()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "tokens.css").write_text(css(tokens), encoding="utf-8")
    (OUT / "didit_tokens.dart").write_text(dart(tokens), encoding="utf-8")
    (OUT / "tokens.resolved.json").write_text(json.dumps(tokens, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"{len(tokens)} tokens -> {OUT.relative_to(ROOT)}")
    if "--check" in sys.argv:
        bad = 0
        for mode, fg, bg, r, need, use in contrast(tokens):
            ok = r >= need
            bad += not ok
            print(f"{mode:5} {fg:14} on {bg:13} {r:5.2f}  need {need}  {'OK' if ok else 'LOW'}  {use}")
        sys.exit(1 if bad else 0)


if __name__ == "__main__":
    main()
