"""Persian pixel numerals for large numbers (streak, adherence, level). D-058.

Grid follows the Persian wordmark: 7 rows tall, vertical strokes 2 units wide,
horizontal strokes 1 unit tall. Digits are always laid out left to right
(most significant first), even inside RTL text.

    python3 tools/design-system/pixel_numerals.py            # write outputs
    python3 tools/design-system/pixel_numerals.py --preview  # also write a PNG preview
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs/07-design-system/numerals"
HEIGHT = 7
GAP = 1  # units between glyphs

GLYPHS = {
    "۰": [".....", ".....", ".....", ".###.", "##.##", ".###.", "....."],
    "۱": ["##", "##", "##", "##", "##", "##", "##"],
    "۲": ["##.##", "##.##", "#####", "##...", "##...", "##...", "##..."],
    "۳": ["##.#.##", "##.#.##", "#######", "##.....", "##.....", "##.....", "##....."],
    "۴": ["##..##", "##.##.", "####..", "######", "##....", "##....", "##...."],
    "۵": ["..##..", ".####.", "##..##", "##..##", "##..##", "##..##", ".####."],
    "۶": ["#####", "##.##", "...##", "..##.", "..##.", ".##..", ".##.."],
    "۷": ["##..##", "##..##", "##..##", ".####.", ".####.", "..##..", "..##.."],
    "۸": ["..##..", "..##..", ".####.", ".####.", "##..##", "##..##", "##..##"],
    "۹": [".####", "##.##", "##.##", ".####", "...##", "...##", "...##"],
    "٪": ["##...#", "##..##", "...##.", "..##..", ".##...", "##..##", "#...##"],
}
LATIN = dict(zip("0123456789%", GLYPHS))


def check():
    for ch, rows in GLYPHS.items():
        assert len(rows) == HEIGHT, ch
        assert len({len(r) for r in rows}) == 1, ch


def rects(rows, ox=0, oy=0):
    """Merge each row's runs into rects: (x, y, w, h) in grid units."""
    out = []
    for y, row in enumerate(rows):
        x = 0
        while x < len(row):
            if row[x] == "#":
                s = x
                while x < len(row) and row[x] == "#":
                    x += 1
                out.append((ox + s, oy + y, x - s, 1))
            else:
                x += 1
    return out


def svg(rows, unit=4, title=""):
    w = len(rows[0])
    d = "".join(f"M{x * unit} {y * unit}h{rw * unit}v{rh * unit}h-{rw * unit}z" for x, y, rw, rh in rects(rows))
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w * unit} {HEIGHT * unit}" '
            f'width="{w * unit}" height="{HEIGHT * unit}" shape-rendering="crispEdges" fill="currentColor">'
            f"<title>{title}</title><path d=\"{d}\"/></svg>\n")


def layout(text):
    """Rows for a whole number string, digits left to right."""
    text = "".join(c if c in GLYPHS else LATIN.get(c, "") for c in text)
    glyphs = [GLYPHS[c] for c in text]
    rows = ["" for _ in range(HEIGHT)]
    for i, g in enumerate(glyphs):
        for y in range(HEIGHT):
            rows[y] += ("." * GAP if i else "") + g[y]
    return rows


def write():
    check()
    (OUT / "svg").mkdir(parents=True, exist_ok=True)
    for ch, rows in GLYPHS.items():
        name = "percent" if ch == "٪" else f"digit-{'۰۱۲۳۴۵۶۷۸۹'.index(ch)}"
        (OUT / "svg" / f"{name}.svg").write_text(svg(rows, title=ch), encoding="utf-8")
    data = {
        "$description": "Didit Persian pixel numerals. Rows top to bottom, '#' = filled unit. "
                        "Render at an integer unit (default 4dp) with no anti-aliasing. Lay out left to right.",
        "height": HEIGHT, "gap": GAP, "defaultUnitDp": 4,
        "glyphs": {ch: {"width": len(rows[0]), "rows": rows} for ch, rows in GLYPHS.items()},
    }
    (OUT / "numerals.json").write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    dart = ["// GENERATED by tools/design-system/pixel_numerals.py. Do not edit by hand.",
            "// Persian pixel numerals: rows top to bottom, '#' = one unit. Lay out left to right.", "",
            "abstract final class DdNumerals {",
            f"  static const int height = {HEIGHT};",
            f"  static const int gap = {GAP};",
            "  static const Map<String, List<String>> glyphs = {"]
    for ch, rows in GLYPHS.items():
        dart.append(f"    '{ch}': [" + ", ".join(f"'{r}'" for r in rows) + "],")
    dart += ["  };", "", "  /// Western digits and % map to their Persian glyphs.",
             "  static const Map<String, String> fromLatin = {"]
    dart += [f"    '{a}': '{b}'," for a, b in LATIN.items()]
    dart += ["  };", "}", ""]
    (OUT / "didit_numerals.dart").write_text("\n".join(dart), encoding="utf-8")


def preview(path, samples=("۰۱۲۳۴۵۶۷۸۹٪", "۲۱", "۶۶", "۱۰۰", "۳۶۵", "۷۳٪"), unit=8):
    from PIL import Image, ImageDraw
    lines = [layout(s) for s in samples]
    pad = 2
    W = max(len(r[0]) for r in lines) + 2 * pad
    H = len(lines) * (HEIGHT + 3) + pad
    themes = [((241, 252, 234), (6, 23, 32)), ((6, 23, 32), (223, 248, 207))]
    im = Image.new("RGB", (W * unit * 2, H * unit), themes[0][0])
    d = ImageDraw.Draw(im)
    for t, (bg, fg) in enumerate(themes):
        ox = t * W * unit
        d.rectangle([ox, 0, ox + W * unit - 1, H * unit - 1], fill=bg)
        for i, rows in enumerate(lines):
            for x, y, rw, rh in rects(rows, pad, pad + i * (HEIGHT + 3)):
                d.rectangle([ox + x * unit, y * unit, ox + (x + rw) * unit - 1, (y + rh) * unit - 1], fill=fg)
    im.save(path)


if __name__ == "__main__":
    write()
    if "--preview" in sys.argv:
        preview(OUT / "preview.png")
    print(f"wrote {OUT}")
